// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	User  *User  `json:"user"`
	Token string `json:"token"`
}

type Event struct {
	ID          int64    `json:"id"`
	Task        *Task    `json:"task"`
	Timing      []string `json:"timing"`
	FullPomo    bool     `json:"fullPomo"`
	TimeCreated string   `json:"timeCreated"`
	TimeUpdated string   `json:"timeUpdated"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type PomoInput struct {
	TaskID int64 `json:"taskId"`
}

type Task struct {
	ID            int64   `json:"id"`
	Name          string  `json:"name"`
	Description   *string `json:"description,omitempty"`
	Status        int32   `json:"status"`
	TimeCreated   string  `json:"timeCreated"`
	TimeUpdated   string  `json:"timeUpdated"`
	TimeCompleted *string `json:"timeCompleted,omitempty"`
	DueDate       *string `json:"dueDate,omitempty"`
}

type TaskInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	DueDate     *string `json:"dueDate,omitempty"`
}

type TaskUpdateInput struct {
	TaskID     int64      `json:"taskId"`
	TaskFields *TaskInput `json:"taskFields"`
}
