// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type AuthPayload struct {
	User  *User  `json:"user"`
	Token string `json:"token"`
}

type Event struct {
	ID      int64      `json:"id"`
	TaskID  int64      `json:"taskID"`
	StartAt time.Time  `json:"startAt"`
	EndAt   *time.Time `json:"endAt,omitempty"`
}

type EventQueryInput struct {
	Limit    *int32 `json:"limit,omitempty"`
	OrderAsc *bool  `json:"orderAsc,omitempty"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type QueryTaskInput struct {
	Status  []TaskStatus      `json:"status,omitempty"`
	OrderBy *QueryTaskOrderBy `json:"orderBy,omitempty"`
}

type QueryTaskOrderBy struct {
	Field     QueryTaskOrderField `json:"field"`
	Direction *OrderDirection     `json:"direction,omitempty"`
}

type QueryUserTaskResult struct {
	User  *UserPublic `json:"user"`
	Tasks []*Task     `json:"tasks,omitempty"`
	Doing *Task       `json:"doing,omitempty"`
}

type QueryUserTasksInput struct {
	Username string `json:"username"`
}

type Task struct {
	ID          int64      `json:"id"`
	Name        string     `json:"name"`
	Description *string    `json:"description,omitempty"`
	Status      TaskStatus `json:"status"`
	CreatedAt   time.Time  `json:"createdAt"`
	UpdatedAt   time.Time  `json:"updatedAt"`
	DueDate     *time.Time `json:"dueDate,omitempty"`
	Events      []*Event   `json:"events,omitempty"`
}

type TaskCreateInput struct {
	Name        string     `json:"name"`
	Description *string    `json:"description,omitempty"`
	DueDate     *time.Time `json:"dueDate,omitempty"`
}

type TaskUpdateInput struct {
	Name        *string     `json:"name,omitempty"`
	Description *string     `json:"description,omitempty"`
	DueDate     *time.Time  `json:"dueDate,omitempty"`
	Status      *TaskStatus `json:"status,omitempty"`
}

type UserPublic struct {
	ID            int64   `json:"id"`
	Username      *string `json:"username,omitempty"`
	Name          *string `json:"name,omitempty"`
	RunningTaskID *int64  `json:"runningTaskID,omitempty"`
}

type UserUpdateInput struct {
	Name     *string `json:"name,omitempty"`
	Username *string `json:"username,omitempty"`
	Password *string `json:"password,omitempty"`
}

type OrderDirection string

const (
	OrderDirectionAsc  OrderDirection = "ASC"
	OrderDirectionDesc OrderDirection = "DESC"
)

var AllOrderDirection = []OrderDirection{
	OrderDirectionAsc,
	OrderDirectionDesc,
}

func (e OrderDirection) IsValid() bool {
	switch e {
	case OrderDirectionAsc, OrderDirectionDesc:
		return true
	}
	return false
}

func (e OrderDirection) String() string {
	return string(e)
}

func (e *OrderDirection) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderDirection", str)
	}
	return nil
}

func (e OrderDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type QueryTaskOrderField string

const (
	QueryTaskOrderFieldCreatedAt QueryTaskOrderField = "CREATED_AT"
	QueryTaskOrderFieldUpdatedAt QueryTaskOrderField = "UPDATED_AT"
	QueryTaskOrderFieldID        QueryTaskOrderField = "ID"
	QueryTaskOrderFieldStatus    QueryTaskOrderField = "STATUS"
)

var AllQueryTaskOrderField = []QueryTaskOrderField{
	QueryTaskOrderFieldCreatedAt,
	QueryTaskOrderFieldUpdatedAt,
	QueryTaskOrderFieldID,
	QueryTaskOrderFieldStatus,
}

func (e QueryTaskOrderField) IsValid() bool {
	switch e {
	case QueryTaskOrderFieldCreatedAt, QueryTaskOrderFieldUpdatedAt, QueryTaskOrderFieldID, QueryTaskOrderFieldStatus:
		return true
	}
	return false
}

func (e QueryTaskOrderField) String() string {
	return string(e)
}

func (e *QueryTaskOrderField) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = QueryTaskOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid QueryTaskOrderField", str)
	}
	return nil
}

func (e QueryTaskOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type TaskStatus string

const (
	TaskStatusNotStarted TaskStatus = "NOT_STARTED"
	TaskStatusDoing      TaskStatus = "DOING"
	TaskStatusDone       TaskStatus = "DONE"
	TaskStatusPaused     TaskStatus = "PAUSED"
)

var AllTaskStatus = []TaskStatus{
	TaskStatusNotStarted,
	TaskStatusDoing,
	TaskStatusDone,
	TaskStatusPaused,
}

func (e TaskStatus) IsValid() bool {
	switch e {
	case TaskStatusNotStarted, TaskStatusDoing, TaskStatusDone, TaskStatusPaused:
		return true
	}
	return false
}

func (e TaskStatus) String() string {
	return string(e)
}

func (e *TaskStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskStatus", str)
	}
	return nil
}

func (e TaskStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
