package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"sort"
	"time"

	"github.com/Shopify/hoff"
	"github.com/todopeer/backend/graph/model"
	"github.com/todopeer/backend/orm"
	"github.com/todopeer/backend/services/auth"
	"github.com/todopeer/backend/util/highorder"
)

// Events is the resolver for the events field.
func (r *queryResolver) Events(ctx context.Context, day string) (*model.QueryEventsResult, error) {
	startAt, err := time.Parse(time.DateOnly, day)
	if err != nil {
		return nil, err
	}

	user := auth.UserFromContext(ctx)
	events, err := r.eventOrm.GetUserEventsByDay(user.ID, startAt)
	if err != nil {
		return nil, err
	}

	taskIdsWithDup := hoff.Map(events, func(e *orm.Event) int64 { return *e.TaskID })
	sort.Slice(taskIdsWithDup, func(i, j int) bool { return taskIdsWithDup[i] < taskIdsWithDup[j] })
	taskIds := highorder.Uniq(taskIdsWithDup)
	tasks, err := r.taskOrm.GetTasksByIDs(taskIds)
	if err != nil {
		return nil, err
	}

	return &model.QueryEventsResult{
		Tasks:  hoff.Map(tasks, model.ConvertToGqlTaskModel),
		Events: hoff.Map(events, model.ConvertToGqlEventModel),
	}, nil
}
