package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"fmt"

	"github.com/flyfy1/diarier/graph"
	"github.com/flyfy1/diarier/graph/model"
)

// PomoStart is the resolver for the pomoStart field.
func (r *mutationResolver) PomoStart(ctx context.Context, input model.PomoInput) (*model.Event, error) {
	panic(fmt.Errorf("not implemented: PomoStart - pomoStart"))
}

// PomoPause is the resolver for the pomoPause field.
func (r *mutationResolver) PomoPause(ctx context.Context, input model.PomoInput) (*model.Event, error) {
	panic(fmt.Errorf("not implemented: PomoPause - pomoPause"))
}

// Ping is the resolver for the ping field.
func (r *queryResolver) Ping(ctx context.Context) (bool, error) {
	panic(fmt.Errorf("not implemented: Ping - ping"))
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
